import type { Metadata } from 'next';
import './globals.scss';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
	title: 'Mira',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				{children} <ToastContainer />
			</body>
		</html>
	);
}
